# Generated by Django 5.2.3 on 2025-06-27 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'permissions': [('can_delete_file', 'Can delete file'), ('can_download_file', 'Can download file')]},
        ),
    ]
